# Используем официальный образ Node.js в качестве базового образа для сборки Angular приложения
FROM node:latest AS build

WORKDIR /usr/local/app

RUN npm install

RUN npm run build

FROM nginx:latest

COPY --from=build /usr/local/app/dist/lab8-weather /usr/share/nginx/html
EXPOSE 80